### ISSUE TITLE
Error: redirect_uri_mismatch

### ISSUE THREAD

**Issue by brittocj** [shashank-sharma/google-oauth-mail#1]
![Screenshot 2019-04-19 at 2 12 38 PM](https://user-images.githubusercontent.com/1892301/56416015-35069980-62ad-11e9-8328-4fd2ad75e1c3.png)
When tried clicking on Google link it shows "Error: redirect_uri_mismatch".

Please help.

**Comment by shashank-sharma** [comment]
@brittocj Hi
I suggest you read this blog first for better understanding: https://www.geeksforgeeks.org/python-django-google-authentication-and-fetching-mails-from-scratch/

Let me know if that helps

**Comment by rahulsanoria** [comment]
/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail
/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f6d64943ae8>
Traceback (most recent call last):
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 121, in _loadfile
    with open(filename, 'r') as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'cred.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/gfgauth/models.py", line 4, in <module>
    from oauth2client.contrib.django_util.models import CredentialsField
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/contrib/django_util/__init__.py", line 365, in <module>
    oauth2_settings = OAuth2Settings(django.conf.settings)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/contrib/django_util/__init__.py", line 341, in __init__
    info = _get_oauth2_client_id_and_secret(settings_instance)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/contrib/django_util/__init__.py", line 277, in _get_oauth2_client_id_and_secret
    return _load_client_secrets(secret_json)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/contrib/django_util/__init__.py", line 255, in _load_client_secrets
    client_type, client_info = clientsecrets.loadfile(filename)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 125, in _loadfile
    exc.strerror, exc.errno)
oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file', 'cred.json', 'No such file or directory', 2)
/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f850a2a00d0>
Traceback (most recent call last):
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 112, in inner_run
    autoreload.raise_last_exception()
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate
    app_config.import_models()
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/gfgauth/models.py", line 4, in <module>
    from oauth2client.contrib.django_util.models import CredentialsField
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/contrib/django_util/__init__.py", line 365, in <module>
    oauth2_settings = OAuth2Settings(django.conf.settings)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/contrib/django_util/__init__.py", line 341, in __init__
    info = _get_oauth2_client_id_and_secret(settings_instance)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/contrib/django_util/__init__.py", line 277, in _get_oauth2_client_id_and_secret
    return _load_client_secrets(secret_json)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/contrib/django_util/__init__.py", line 255, in _load_client_secrets
    client_type, client_info = clientsecrets.loadfile(filename)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile
    return _loadfile(filename)
  File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 122, in _loadfile
    obj = json.load(fp)
  File "/usr/lib/python3.6/json/__init__.py", line 299, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 394 (char 393)

**Comment by Omkar19202** [comment]
> /home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail /home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail Unhandled exception in thread started by <function check_errors..wrapper at 0x7f6d64943ae8> Traceback (most recent call last): File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 121, in _loadfile with open(filename, 'r') as fp: FileNotFoundError: [Errno 2] No such file or directory: 'cred.json'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last): File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper fn(*args, **kwargs) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 112, in inner_run autoreload.raise_last_exception() File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception raise _exception[1] File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/core/management/**init**.py", line 327, in execute autoreload.check_errors(django.setup)() File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper fn(*args, **kwargs) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/**init**.py", line 24, in setup apps.populate(settings.INSTALLED_APPS) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate app_config.import_models() File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models self.models_module = import_module(models_module_name) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 994, in _gcd_import File "", line 971, in _find_and_load File "", line 955, in _find_and_load_unlocked File "", line 665, in _load_unlocked File "", line 678, in exec_module File "", line 219, in _call_with_frames_removed File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/gfgauth/models.py", line 4, in from oauth2client.contrib.django_util.models import CredentialsField File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/contrib/django_util/**init**.py", line 365, in oauth2_settings = OAuth2Settings(django.conf.settings) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/contrib/django_util/**init**.py", line 341, in **init** info = _get_oauth2_client_id_and_secret(settings_instance) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/contrib/django_util/**init**.py", line 277, in _get_oauth2_client_id_and_secret return _load_client_secrets(secret_json) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/contrib/django_util/**init**.py", line 255, in _load_client_secrets client_type, client_info = clientsecrets.loadfile(filename) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile return _loadfile(filename) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 125, in _loadfile exc.strerror, exc.errno) oauth2client.clientsecrets.InvalidClientSecretsError: ('Error opening file', 'cred.json', 'No such file or directory', 2) /home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail Unhandled exception in thread started by <function check_errors..wrapper at 0x7f850a2a00d0> Traceback (most recent call last): File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper fn(*args, **kwargs) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 112, in inner_run autoreload.raise_last_exception() File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 248, in raise_last_exception raise _exception[1] File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/core/management/**init**.py", line 327, in execute autoreload.check_errors(django.setup)() File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper fn(*args, **kwargs) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/**init**.py", line 24, in setup apps.populate(settings.INSTALLED_APPS) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/apps/registry.py", line 112, in populate app_config.import_models() File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/django/apps/config.py", line 198, in import_models self.models_module = import_module(models_module_name) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/importlib/**init**.py", line 126, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "", line 994, in _gcd_import File "", line 971, in _find_and_load File "", line 955, in _find_and_load_unlocked File "", line 665, in _load_unlocked File "", line 678, in exec_module File "", line 219, in _call_with_frames_removed File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/gfgauth/models.py", line 4, in from oauth2client.contrib.django_util.models import CredentialsField File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/contrib/django_util/**init**.py", line 365, in oauth2_settings = OAuth2Settings(django.conf.settings) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/contrib/django_util/**init**.py", line 341, in **init** info = _get_oauth2_client_id_and_secret(settings_instance) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/contrib/django_util/**init**.py", line 277, in _get_oauth2_client_id_and_secret return _load_client_secrets(secret_json) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/contrib/django_util/**init**.py", line 255, in _load_client_secrets client_type, client_info = clientsecrets.loadfile(filename) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 165, in loadfile return _loadfile(filename) File "/home/rahul/Desktop/workspace/gmail_integration/google-oauth-mail/env/lib/python3.6/site-packages/oauth2client/clientsecrets.py", line 122, in _loadfile obj = json.load(fp) File "/usr/lib/python3.6/json/**init**.py", line 299, in load parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw) File "/usr/lib/python3.6/json/**init**.py", line 354, in loads return _default_decoder.decode(s) File "/usr/lib/python3.6/json/decoder.py", line 339, in decode obj, end = self.raw_decode(s, idx=_w(s, 0).end()) File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode raise JSONDecodeError("Expecting value", s, err.value) from None json.decoder.JSONDecodeError: Expecting value: line 1 column 394 (char 393)

How did solve this error?
